// GENERATED by @edgedb/generate v0.5.6

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<persons[is info]": $.LinkDesc<$info, $.Cardinality.Many, {}, false, false,  false, false>;
  "<persons": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $User = $.makeType<$User>(_.spec, "1784218b-e194-11ef-beff-a932f94faae7", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);

export type $infoλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "persons": $.LinkDesc<$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $info = $.ObjectType<"default::info", $infoλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $info = $.makeType<$info>(_.spec, "1787740e-e194-11ef-ae3a-73658dbfb88b", _.syntax.literal);

const info: $.$expr_PathNode<$.TypeSet<$info, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($info, $.Cardinality.Many), null);



export { $User, User, $info, info };

type __defaultExports = {
  "User": typeof User;
  "info": typeof info
};
const __defaultExports: __defaultExports = {
  "User": User,
  "info": info
};
export default __defaultExports;
